server:
  port: 8081
jwt:
    secret: secretKey123
    jwtExpirationInMs: 300000
spring:
  datasource:
    url: jdbc:mysql://localhost/meditationattendance
    username: root
    password: foodhub
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect