server:
  port: 8090
jwt:
    secret: secretKey123
    jwtExpirationInMs: 3000000
spring:
  application:
    name: meditation-attendance-server
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=meditationattendance;integratedSecurity=true;
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2008Dialect

basicAuthenConfig:
  urlPattern: /attendances/**
  username: username
  password: password